---
# Bali zkEVM Testnet (built on top of Sepolia)

## Erigon configuration
# The name of the testnet to join.
chain: hermez-cardona-internal
# The data directory for the databases.
datadir: $HOME/Documents/work/clients/cdk-erigon/tmp2
# The port to listen and serve BitTorrent protocol.
torrent.port: 42070
# The internal grpc API used by erigon components (txpool, rpcdaemon, sentry, downloader, etc.) to connect and communicate efficiently.
private.api.addr: localhost:9092

# Disable the internal txpool and block producer (experimental).
txpool.disable: true
# Enable external consensus.
externalcl: true


## zkEVM configuration
# The RPC rate limit in requests per second.
zkevm.rpc-ratelimit: 250
# The stream version indicator (1: PreBigEndian, 2: BigEndian) of the zkevm data stream.
zkevm.datastream-version: 2 # default value


### L1 configuration
# The L1 chain id.
zkevm.l1-chain-id: 11155111
# The L1 RPC endpoint
zkevm.l1-rpc-url: https://rpc.sepolia.org
# The address of the L1 chain.
zkevm.l1-rollup: "0x89BA0Ed947a88fe43c22Ae305C0713eC8a7Eb361"

#### L1 contracts
# The address of the Polygon Rollup Manager contract on L1.
zkevm.l1-polygon-rollup-manager: "0xE2EF6215aDc132Df6913C8DD16487aBF118d1764"
# The address of the Matic contract on L1.
zkevm.l1-matic-contract-address: "0xbA59560D9B3a697745695A01144536514afE0e2B"
# The address of the Global Exit Root Manager contract on L1.
zkevm.l1-ger-manager-contract-address: "0x2968D6d736178f8FE7393CC33C87f29D9C287e78"

#### L1 topics
# The L1 topic for verification.
zkevm.l1-topic-verification: "0x9c72852172521097ba7e1482e6b44b351323df0155f97f4ea18fcec28e1f5966"
# The L1 topic for sequencing.
zkevm.l1-topic-sequence: "0x3e54d0825ed78523037d00a81759237eb436ce774bd546993ee67a1b67b6e766"

#### L1 query parameters
# The block range used to filter verifications and sequences on L1.
zkevm.l1-block-range: 20000 # default value
# The delay (in ms) between queries for verifications and sequences on L1.
zkevm.l1-query-delay: 6000 # default value
# The first block to start syncing from on L1.
zkevm.l1-first-block: 4794475


### L2 configuration
# The L2 chain id.
zkevm.l2-chain-id: 2440
# The RPC endpoint of the sequencer on L2.
zkevm.l2-sequencer-rpc-url: https://rpc.internal.zkevm-rpc.com
# The URL endpoint of the datastreamer on L2.
# This component is responsible for sending L2 blocks.
zkevm.l2-datastreamer-url: datastream.internal.zkevm-rpc.com:6900


## RPC configurtion
# The HTTP-RPC server listening port.
http.addr: 0.0.0.0
# The APIs offered over the HTTP-RPC interface.
http.api: [eth,debug,net,trace,web3,erigon,zkevm]
