# Configuration shared by all CDK-Erigon nodes.

## [HTTP-RPC Server]
# The HTTP-RPC server listening port.
http.addr: 0.0.0.0
# The APIs offered over the HTTP-RPC interface.
http.api: [eth,debug,net,trace,web3,erigon,zkevm]

## [Other]
# Disable the internal txpool and block producer (experimental).
txpool.disable: true
# Enable external consensus.
externalcl: true

## [zkEVM L1 topics]
# The L1 topic for verification.
zkevm.l1-topic-verification: "0x9c72852172521097ba7e1482e6b44b351323df0155f97f4ea18fcec28e1f5966"
# The L1 topic for sequencing.
zkevm.l1-topic-sequence: "0x3e54d0825ed78523037d00a81759237eb436ce774bd546993ee67a1b67b6e766"
